var canvas1 = document.getElementById("uno");
var miDibujo = canvas1.getContext("2d");
var X = canvas1.width/2;
var Y = canvas1.height/2;
var r = 50;
var aPartida = (Math.PI / 180) * 220;
var aFinal =  (Math.PI / 180) * 320;
miDibujo.strokeStyle = "orange";
miDibujo.lineWidth = 15;
miDibujo.arc(X,Y,r,aPartida,aFinal,false);
miDibujo.stroke();